In [1]:
import numpy as np
np.__version__

'1.10.1'

In [2]:
np.empty([2,2], int)

array([[42556752,        0],
       [58938792,        0]])

In [3]:
X = np.array([[1,2,3], [4,5,6]], np.int32)
np.empty_like(X)

array([[     10240,  728956928, 1124073472],
       [1934974010, 1551069797, 1870227800]])

In [4]:
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [5]:
np.ones([3,2], float)

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [6]:
X = np.arange(4, dtype=np.int64)
np.ones_like(X)

array([1, 1, 1, 1], dtype=int64)

In [7]:
np.zeros([3,2], float)

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [8]:
x = np.arange(4, dtype=np.int64)
np.zeros_like(x)

array([0, 0, 0, 0], dtype=int64)

In [9]:
np.ones([2, 5], dtype=np.uint32) * 6

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

In [10]:
x = np.arange(4, dtype=np.int64)
np.full_like(x, 6)

array([6, 6, 6, 6], dtype=int64)

In [11]:
np.array([1, 2, 3])

array([1, 2, 3])

In [12]:
x = [1, 2]
np.asarray(x)

array([1, 2])

In [13]:
X = np.array([[1, 2], [3, 4]])
np.asmatrix(X)

matrix([[1, 2],
        [3, 4]])

In [14]:
x = [1, 2]
np.asfarray(x)

array([ 1.,  2.])

In [15]:
x = np.array([30])
np.asscalar(x)

30

In [16]:
x = np.array([1, 2, 3])
y = np.copy(x)
print id(x), x
print id(y), y

70574128 [1 2 3]
70574208 [1 2 3]


In [17]:
np.arange(2, 101, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [18]:
np.linspace(3, 10, 50)

array([  3.        ,   3.14285714,   3.28571429,   3.42857143,
         3.57142857,   3.71428571,   3.85714286,   4.        ,
         4.14285714,   4.28571429,   4.42857143,   4.57142857,
         4.71428571,   4.85714286,   5.        ,   5.14285714,
         5.28571429,   5.42857143,   5.57142857,   5.71428571,
         5.85714286,   6.        ,   6.14285714,   6.28571429,
         6.42857143,   6.57142857,   6.71428571,   6.85714286,
         7.        ,   7.14285714,   7.28571429,   7.42857143,
         7.57142857,   7.71428571,   7.85714286,   8.        ,
         8.14285714,   8.28571429,   8.42857143,   8.57142857,
         8.71428571,   8.85714286,   9.        ,   9.14285714,
         9.28571429,   9.42857143,   9.57142857,   9.71428571,
         9.85714286,  10.        ])

In [19]:
np.logspace(3., 10., 50, endpoint = False)

array([  1.00000000e+03,   1.38038426e+03,   1.90546072e+03,
         2.63026799e+03,   3.63078055e+03,   5.01187234e+03,
         6.91830971e+03,   9.54992586e+03,   1.31825674e+04,
         1.81970086e+04,   2.51188643e+04,   3.46736850e+04,
         4.78630092e+04,   6.60693448e+04,   9.12010839e+04,
         1.25892541e+05,   1.73780083e+05,   2.39883292e+05,
         3.31131121e+05,   4.57088190e+05,   6.30957344e+05,
         8.70963590e+05,   1.20226443e+06,   1.65958691e+06,
         2.29086765e+06,   3.16227766e+06,   4.36515832e+06,
         6.02559586e+06,   8.31763771e+06,   1.14815362e+07,
         1.58489319e+07,   2.18776162e+07,   3.01995172e+07,
         4.16869383e+07,   5.75439937e+07,   7.94328235e+07,
         1.09647820e+08,   1.51356125e+08,   2.08929613e+08,
         2.88403150e+08,   3.98107171e+08,   5.49540874e+08,
         7.58577575e+08,   1.04712855e+09,   1.44543977e+09,
         1.99526231e+09,   2.75422870e+09,   3.80189396e+09,
         5.24807460e+09,

In [20]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
np.diag(X)

array([ 0,  5, 10])

In [21]:
np.diagflat([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [22]:
np.tri(3, 5, -1)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

In [23]:
np.tril(np.arange(1, 13).reshape(4, 3), -1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [24]:
np.tri(10, 1)

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [25]:
np.triu(np.arange(1, 13).reshape(4, 3), -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [26]:
print 'That was all for "Array creation routines".'

That was all for "Array creation routines".


In [27]:
import numpy as np

In [28]:
x = np.ones([10, 10, 3])
out = np.reshape(x,[-1, 150])
print out

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  

In [29]:
x = np.array([[1, 2, 3], [4, 5, 6]])
out1 = np.ravel(x, order='F')
out2 = x.flatten(order="F")
print out2

[1 4 2 5 3 6]


In [30]:
x = np.array([[1, 2, 3], [4, 5, 6]])
out1 = x.flat[4]
out2 = np.ravel(x)[4]
print out2

5


In [31]:
x = np.zeros((3, 4, 5))
out1 = np.swapaxes(x, 1, 0)
out2 = x.transpose([1, 0, 2])
assert out1.shape == out2.shape
print out1.shape

(4L, 3L, 5L)


In [32]:
x = np.zeros((3, 4))
out1 = np.swapaxes(x, 1, 0)
out2 = x.transpose()
out3 = x.T
assert out1.shape == out2.shape == out3.shape
print out1.shape

(4L, 3L)


In [33]:
x = np.zeros((3, 4))
print np.expand_dims(x, axis=1).shape

(3L, 1L, 4L)


In [34]:
x = np.zeros((3, 4, 1))
print np.squeeze(x).shape

(3L, 4L)


In [35]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
out1 = np.concatenate((x, y), 1)
out2 = np.hstack((x, y))
assert np.allclose(out1, out2)
print out2

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [36]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
out1 = np.concatenate((x, y), 0)
out2 = np.vstack((x, y))
assert np.allclose(out1, out2)
print out2

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [37]:
x = np.array((1,2,3))
y = np.array((4,5,6))
out1 = np.column_stack((x, y))
out2 = np.dstack((x, y))
out3 = np.vstack((x, y)).T
assert np.allclose(out1, out2)
assert np.allclose(out2, out3)
print out1

[[1 4]
 [2 5]
 [3 6]]


In [38]:
x = np.array([[1],[2],[3]])
y = np.array([[4],[5],[6]])
out = np.dstack((x, y))
print out

[[[1 4]]

 [[2 5]]

 [[3 6]]]


In [39]:
x = np.arange(1, 10)
print np.split(x, [4, 6])

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


In [40]:
x = np.arange(16).reshape(2, 2, 4)
out1 = np.split(x, [3], axis=2)
out2 = np.dsplit(x, [3])
print out2

[array([[[ 0,  1,  2],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [12, 13, 14]]]), array([[[ 3],
        [ 7]],

       [[11],
        [15]]])]


In [41]:
x = np.arange(16).reshape((4, 4))
out1 = np.hsplit(x, [2])
out2 = np.split(x, [2], 1)
assert np.allclose(out1[0], out2[0])
assert np.allclose(out1[1], out2[1])
print out1

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [42]:
x = np.arange(16).reshape((4, 4))
out1 = np.vsplit(x, 2)
out2 = np.split(x, 2, 0)
assert np.allclose(out1[0], out2[0])
assert np.allclose(out1[1], out2[1])
print out1

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [43]:
x = np.array([0, 1, 2])
out1 = np.tile(x, [2, 2])
out2 = np.resize(x, [2, 6])
assert np.allclose(out1, out2)
print out1

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


In [44]:
x = np.array([0, 1, 2])
print np.repeat(x, 2)

[0 0 1 1 2 2]


In [45]:
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
out = np.trim_zeros(x)
print out

[1 2 3 0 2 1]


In [46]:
x = np.array([2, 2, 1, 5, 4, 5, 1, 2, 3])
u, indices = np.unique(x, return_index = False, return_counts = True)
print u, indices

[1 2 3 4 5] [2 3 1 1 2]


In [47]:
x = np.array([[1,2], [3,4]])
out1 = np.fliplr(x)
out2 = x[:, ::-1]
assert np.allclose(out1, out2)
print out1

[[2 1]
 [4 3]]


In [48]:
x = np.array([[1,2], [3,4]])
out1 = np.flipud(x)
out2 = x[::-1, :]
assert np.allclose(out1, out2)
print out1

[[3 4]
 [1 2]]


In [49]:
x = np.array([[1,2], [3,4]])
out = np.rot90(x)
print out

[[2 4]
 [1 3]]


In [50]:
x = np.arange(1, 9).reshape([2, 4])
print np.roll(x, 1, axis=1)

[[4 1 2 3]
 [8 5 6 7]]


In [51]:
print 'That was all for "Array manipulation routines".'

That was all for "Array manipulation routines".


In [52]:
np.lookfor('linear algebra')

Search results for 'linear algebra'
-----------------------------------
numpy.linalg.solve
    Solve a linear matrix equation, or system of linear scalar equations.
numpy.poly
    Find the coefficients of a polynomial with the given sequence of roots.
numpy.restoredot
    Restore `dot`, `vdot`, and `innerproduct` to the default non-BLAS
numpy.linalg.eig
    Compute the eigenvalues and right eigenvectors of a square array.
numpy.linalg.cond
    Compute the condition number of a matrix.
numpy.linalg.eigh
    Return the eigenvalues and eigenvectors of a Hermitian or symmetric matrix.
numpy.linalg.pinv
    Compute the (Moore-Penrose) pseudo-inverse of a matrix.
numpy.linalg.LinAlgError
    Generic Python-exception-derived object raised by linalg functions.


In [53]:
np.info(np.dot)

dot(a, b, out=None)

Dot product of two arrays.

For 2-D arrays it is equivalent to matrix multiplication, and for 1-D
arrays to inner product of vectors (without complex conjugation). For
N dimensions it is a sum product over the last axis of `a` and
the second-to-last of `b`::

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

Parameters
----------
a : array_like
    First argument.
b : array_like
    Second argument.
out : ndarray, optional
    Output argument. This must have the exact kind that would be returned
    if it was not used. In particular, it must have the right type, must be
    C-contiguous, and its dtype must be the dtype that would be returned
    for `dot(a,b)`. This is a performance feature. Therefore, if these
    conditions are not met, an exception is raised, instead of attempting
    to be flexible.

Returns
-------
output : ndarray
    Returns the dot product of `a` and `b`.  If `a` and `b` are both
    scalars or both 1-D arrays then a scalar is returned; ot

In [54]:
print 'That was all for "Numpy-specific help functions".'

That was all for "Numpy-specific help functions".


In [55]:
x = [1,2]
y = [[4, 1], [2, 2]]
print np.dot(x, y)
print np.dot(y, x)
print np.matmul(x, y)
print np.inner(x, y)
print np.inner(y, x)

[8 5]
[6 6]
[8 5]
[6 6]
[6 6]


In [56]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
print np.dot(y, x)
print np.matmul(y, x)

[[4 1]
 [2 2]
 [1 1]]
[[4 1]
 [2 2]
 [1 1]]


In [57]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
print np.vdot(x, y)
print np.vdot(y, x)
print np.dot(x.flatten(), y.flatten())
print np.inner(x.flatten(), y.flatten())
print (x*y).sum()

30
30
30
30
30


In [58]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
print np.inner(x, y)
print np.inner(y, x)
print np.outer(x, y)
print np.outer(y, x)

abb
abb
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]


In [59]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
L = np.linalg.cholesky(x)
print L
assert np.array_equal(np.dot(L, L.T.conjugate()), x)

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


In [60]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
q, r = np.linalg.qr(x)
print "q=\n", q, "\nr=\n", r
assert np.allclose(np.dot(q, r), x)

q=
[[-0.85714287  0.39428571  0.33142856]
 [-0.42857143 -0.90285712 -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]] 
r=
[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


In [61]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
U, s, V = np.linalg.svd(x, full_matrices=False)
print "U=\n", U, "\ns=\n", s, "\nV=\n", V
assert np.allclose(np.dot(U, np.dot(np.diag(s), V)), x)

U=
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]] 
s=
[ 3.          2.23606801  2.          0.        ] 
V=
[[-0.          0.          1.         -0.          0.        ]
 [ 0.44721359 -0.         -0.         -0.          0.89442718]
 [-0.          1.          0.         -0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]]


In [62]:
x = np.diag((1, 2, 3))
eigenvals = np.linalg.eig(x)[0]
eigenvals_ = np.linalg.eigvals(x)
assert np.array_equal(eigenvals, eigenvals_)
print "eigenvalues are\n", eigenvals
eigenvecs = np.linalg.eig(x)[1]
print "eigenvectors are\n", eigenvecs

eigenvalues are
[ 1.  2.  3.]
eigenvectors are
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [63]:
print np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs)

True


In [64]:
x = np.arange(1, 10).reshape((3, 3))
print np.linalg.norm(x, 'fro')
print np.linalg.cond(x, 'fro')

16.8819430161
4.56177073661e+17


In [65]:
x = np.arange(1, 5).reshape((2, 2))
out1 = np.linalg.det(x)
out2 = x[0, 0] * x[1, 1] - x[0, 1] * x[1, 0]
assert np.allclose(out1, out2)
print out1

-2.0


In [66]:
x = np.eye(4)
out1 = np.linalg.matrix_rank(x)
out2 = np.linalg.svd(x)[1].size
assert out1 == out2
print out1

4


In [67]:
x = np.arange(1, 5).reshape((2, 2))
sign, logdet = np.linalg.slogdet(x)
det = np.linalg.det(x)
assert sign == np.sign(det)
assert logdet == np.log(np.abs(det))
print sign, logdet

-1.0 0.69314718056


In [68]:
x = np.eye(4)
out1 = np.trace(x)
out2 = x.diagonal().sum()
assert out1 == out2
print out1

4.0


In [69]:
x = np.array([[1., 2.], [3., 4.]])
out1 = np.linalg.inv(x)
assert np.allclose(np.dot(x, out1), np.eye(2))
print out1

[[-2.   1. ]
 [ 1.5 -0.5]]


In [70]:
print 'That was all for "Linear algebra (numpy.linalg)".'

That was all for "Linear algebra (numpy.linalg)".


In [71]:
x = np.array([1,2,3])
print np.all(x)

x = np.array([1,0,3])
print np.all(x)

True
False


In [72]:
x = np.array([1,0,0])
print np.any(x)

x = np.array([0,0,0])
print np.any(x)

True
False


In [73]:
x = np.array([1, 0, np.nan, np.inf])
print np.isfinite(x)

[ True  True False False]


In [74]:
x = np.array([1, 0, np.nan, np.inf])
print np.isinf(x)

[False False False  True]


In [75]:
x = np.array([1, 0, np.nan, np.inf])
print np.isnan(x)

[False False  True False]


In [76]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print np.iscomplex(x)

[ True False False False False  True]


In [77]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print np.isreal(x)

[False  True  True  True  True False]


In [78]:
print np.isscalar(3)
print np.isscalar([3])
print np.isscalar(True)

True
False
True


In [79]:
print np.logical_and([True, False], [False, False])
print np.logical_or([True, False, True], [True, False, False])
print np.logical_xor([True, False, True], [True, False, False])
print np.logical_not([True, False, 0, 1])

[False False]
[ True False  True]
[False False  True]
[False  True  True False]


In [80]:
print np.allclose([3], [2.999999])
print np.array_equal([3], [2.999999])

True
False


In [81]:
print np.equal([1, 2], [1, 2.000001])
print np.isclose([1, 2], [1, 2.000001])

[ True False]
[ True  True]


In [82]:
print 'That was all for "Logic functions".'

That was all for "Logic functions".


In [83]:
np.random.rand(3, 2) 

array([[ 0.91394419,  0.17206689],
       [ 0.24219079,  0.39915368],
       [ 0.084485  ,  0.74831786]])

In [84]:
out1 = np.random.randn(1000, 1000)
out2 = np.random.standard_normal((1000, 1000))
out3 = np.random.normal(loc=0.0, scale=1.0, size=(1000, 1000))
assert np.allclose(np.mean(out1), np.mean(out2), atol=0.1)
assert np.allclose(np.mean(out1), np.mean(out3), atol=0.1)
assert np.allclose(np.std(out1), np.std(out2), atol=0.1)
assert np.allclose(np.std(out1), np.std(out3), atol=0.1)
print np.mean(out3)
print np.std(out1)

-0.000371662829704
1.00019849566


In [85]:
np.random.randint(0, 4, (3, 2))

array([[3, 0],
       [3, 1],
       [2, 3]])

In [86]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']

In [87]:
for _ in range(10):
    print np.random.choice(x, p=[.3, .5, .2])

3 out of 10
3 out of 10
5 out of 10
2 out of 10
5 out of 10
5 out of 10
5 out of 10
5 out of 10
3 out of 10
5 out of 10


In [88]:
np.random.choice(10, 3, replace=False)

array([1, 0, 5])

In [89]:
x = np.arange(10)
np.random.shuffle(x)
print x

[6 4 8 1 0 5 7 2 9 3]


In [90]:
print np.random.permutation(10)

[7 4 9 6 0 1 8 5 3 2]


In [91]:
np.random.seed(10)

In [92]:
print 'That was all for "Random sampling (numpy.random)".'

That was all for "Random sampling (numpy.random)".


In [93]:
x = np.array([[1,4],[3,1]])
out = np.sort(x, axis=1)
x.sort(axis=1)
assert np.array_equal(out, x)
print out

[[1 4]
 [1 3]]


In [94]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
print np.lexsort((first_names, surnames))

[1 2 0]


In [95]:
x = np.array([[1,4],[3,1]])
out = np.argsort(x, axis=1)
print out

[[0 1]
 [1 0]]


In [96]:
x = np.random.permutation(10)
print "x =", x
print "\nCheck the fifth element of this new array is 5, the first four elements are all smaller than 5, and 6th through the end are bigger than 5\n", 
out = np.partition(x, 5)
x.partition(5) # in-place equivalent
assert np.array_equal(x, out)
print out

x = [8 2 5 6 3 1 0 7 4 9]

Check the fifth element of this new array is 5, the first four elements are all smaller than 5, and 6th through the end are bigger than 5
[0 1 2 3 4 5 6 7 8 9]


In [97]:
x = np.random.permutation(10)
print "x =", x
partitioned = np.partition(x, 3)
indices = np.argpartition(x, 3)
print "partitioned =", partitioned
print "indices =", partitioned
assert np.array_equiv(x[indices], partitioned)

x = [5 3 4 7 6 8 9 2 1 0]
partitioned = [1 2 0 3 4 5 9 8 7 6]
indices = [1 2 0 3 4 5 9 8 7 6]


In [98]:
x = np.random.permutation(10).reshape(2, 5)
print "x =", x
print "maximum values =", np.max(x, 1)
print "max indices =", np.argmax(x, 1)
print "minimum values =", np.min(x, 1)
print "min indices =", np.argmin(x, 1)

x = [[1 6 2 5 7]
 [8 9 0 3 4]]
maximum values = [7 9]
max indices = [4 1]
minimum values = [1 0]
min indices = [0 2]


In [99]:
x = np.array([[np.nan, 4], [3, 2]])
print "maximum values ignoring NaNs =", np.nanmax(x, 1)
print "max indices =", np.nanargmax(x, 1)
print "minimum values ignoring NaNs =", np.nanmin(x, 1)
print "min indices =", np.nanargmin(x, 1)

maximum values ignoring NaNs = [ 4.  3.]
max indices = [1 0]
minimum values ignoring NaNs = [ 4.  2.]
min indices = [1 1]


In [100]:
x = np.array([[1, 2, 3], [1, 3, 5]])
print "Values bigger than 2 =", x[x>2]
print "Their indices are ", np.nonzero(x > 2)
assert np.array_equiv(x[x>2], x[np.nonzero(x > 2)])
assert np.array_equiv(x[x>2], np.extract(x > 2, x))

Values bigger than 2 = [3 3 5]
Their indices are  (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


In [101]:
x = np.array([[1, 2, 3], [1, 3, 5]])
print np.flatnonzero(x>2)

[2 4 5]


In [102]:
x = np.arange(-5, 4).reshape(3, 3)
print np.where(x <0, 0, x)

[[0 0 0]
 [0 0 0]
 [1 2 3]]


In [103]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x, y)

array([0, 2, 1, 3], dtype=int64)

In [104]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
print np.count_nonzero(x)
assert np.count_nonzero(x) == len(x[x!=0])

5


In [105]:
print 'That was all for "Sorting, searching, and counting".'

That was all for "Sorting, searching, and counting".
